import React, { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import Footer from '../components/layout/Footer';
import { ChevronDown, Brain } from 'lucide-react';

const faqs = [
  {
    question: "Is StudyOS free to use?",
    answer: "Yes! You can sign up and start using StudyOS for free. We offer a generous free tier that allows you to manage your homework and try out our AI tutor. Premium plans are available for advanced features like unlimited file uploads and priority AI processing."
  },
  {
    question: "How does the AI Note-Taker work?",
    answer: "You can upload your PDFs, paste text, or even snap a photo of your textbook. Our AI instantly reads the content, summarizes it, and can automatically generate flashcards and quizzes for you to study."
  },
  {
    question: "Which file formats are supported for uploads?",
    answer: "StudyOS currently supports a wide range of formats including PDF, DOCX, TXT, and image files (JPG, PNG) for automatic text extraction from handwritten notes or textbook pages."
  },
  {
    question: "How does the Smart Homework Tracker differ from a regular calendar?",
    answer: "Unlike a static calendar, our tracker acts as your personal academic assistant. Once you upload your syllabus, it dynamically schedules study sessions, adjusts if you fall behind, and prioritizes assignments based on their difficulty and due dates."
  },
  {
    question: "Can I export the flashcards generated by the AI?",
    answer: "Absolutely! You can study them directly within StudyOS using our spaced-repetition system, or export your AI-generated decks to CSV, Anki, and Quizlet formats to fit your existing workflow."
  },
  {
    question: "What languages does the AI Tutor support?",
    answer: "Our AI Tutor is fluent in over 50 languages. You can upload notes in Spanish, French, Mandarin, and more, and the tutor can explain complex concepts to you in your preferred language."
  },
  {
    question: "Can I use StudyOS on my phone?",
    answer: "Absolutely! StudyOS is designed to work perfectly on your phone's browser with a fully responsive layout, making it easy to review flashcards and check your schedule on the go."
  },
  {
    question: "What is 'Knowledge DNA'?",
    answer: "Knowledge DNA is our unique analytics system. As you study and take quizzes, StudyOS tracks which topics you are struggling with and builds a visual 'DNA' profile. This allows the AI to automatically schedule review sessions focused exactly on your weakest subjects."
  },
  {
    question: "Will StudyOS write my essays for me?",
    answer: "StudyOS is designed as a learning tool to help you understand the material better, not to cheat. It can help you brainstorm, create outlines, and proofread your drafts based on your notes, ensuring you maintain academic integrity."
  },
  {
    question: "Is my data secure?",
    answer: "We take your privacy very seriously. Your notes, files, and personal data are encrypted in transit and at rest. We never sell your data to third parties or use your personal notes to train public AI models."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="min-h-screen bg-[#050505] text-slate-50 overflow-x-hidden font-sans selection:bg-purple-500/30">
      <Helmet>
        <title>FAQ | StudyOS</title>
        <meta name="description" content="Frequently Asked Questions about StudyOS." />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": faqs.map(f => ({
              "@type": "Question",
              "name": f.question,
              "acceptedAnswer": {
                "@type": "Answer",
                "text": f.answer
              }
            }))
          })}
        </script>
      </Helmet>
      
      {/* Immersive Background Effects */}
      <div className="fixed inset-0 z-0 pointer-events-none">
        <div className="absolute top-[-20%] right-[10%] w-[500px] h-[500px] bg-purple-600/10 blur-[120px] rounded-full mix-blend-screen"></div>
        <div className="absolute bottom-[20%] left-[-10%] w-[600px] h-[600px] bg-blue-600/10 blur-[100px] rounded-full mix-blend-screen"></div>
      </div>

      <div className="relative z-10 flex flex-col min-h-screen">
        {/* Navigation */}
        <header className="fixed top-0 left-0 right-0 h-20 border-b border-white/5 bg-[#050505]/60 backdrop-blur-xl z-50">
          <div className="max-w-7xl mx-auto px-6 h-full flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2.5 group">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-white/10 to-white/5 border border-white/10 flex items-center justify-center group-hover:scale-105 transition-transform">
                <Brain className="w-5 h-5 text-white" />
              </div>
              <span className="text-xl font-bold tracking-tight text-white">
                Study<span className="text-white/40">OS</span>
              </span>
            </Link>
            
            <nav className="hidden md:flex items-center gap-8">
              <Link to="/faq" className="text-sm font-medium text-white transition-colors">FAQ</Link>
              <Link to="/support" className="text-sm font-medium text-slate-400 hover:text-white transition-colors">Support</Link>
            </nav>
            
            <div className="flex items-center gap-4">
              <Link to="/login" className="text-sm font-medium text-slate-300 hover:text-white transition-colors hidden sm:block">
                Log in
              </Link>
              <Link to="/login" className="text-sm font-semibold bg-white text-black px-5 py-2.5 rounded-full hover:bg-slate-200 transition-all">
                Start for Free
              </Link>
            </div>
          </div>
        </header>

        <main className="flex-grow pt-32 pb-20 w-full max-w-4xl mx-auto px-6">
          <div className="text-center mb-16 pt-10">
            <div className="inline-flex items-center justify-center px-4 py-1.5 mb-6 rounded-full bg-white/5 border border-white/10 text-sm font-medium text-slate-300">
              Help Center
            </div>
            <h1 className="text-4xl md:text-6xl font-bold mb-6 text-white tracking-tight">Frequently Asked Questions</h1>
            <p className="text-lg md:text-xl text-slate-400 max-w-2xl mx-auto">
              Everything you need to know about StudyOS and how it can help you ace your exams.
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => {
              const isOpen = openIndex === index;
              return (
                <div 
                  key={index} 
                  className={`border rounded-2xl overflow-hidden transition-all duration-300 ${isOpen ? 'bg-white/[0.04] border-white/20 shadow-[0_0_30px_rgba(255,255,255,0.03)]' : 'bg-white/[0.01] border-white/5 hover:border-white/10 hover:bg-white/[0.02]'}`}
                >
                  <button
                    className="w-full px-6 py-5 flex items-center justify-between text-left font-semibold text-lg"
                    onClick={() => setOpenIndex(isOpen ? null : index)}
                  >
                    <span className={`transition-colors ${isOpen ? 'text-white' : 'text-slate-300'}`}>{faq.question}</span>
                    <div className={`w-8 h-8 rounded-full flex items-center justify-center transition-colors ${isOpen ? 'bg-white/10' : 'bg-white/5'}`}>
                      <ChevronDown className={`w-4 h-4 text-slate-400 transition-transform duration-300 ${isOpen ? 'rotate-180 text-white' : ''}`} />
                    </div>
                  </button>
                  
                  <div className={`overflow-hidden transition-all duration-300 ease-in-out ${isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}>
                    <div className="px-6 pb-6 pt-2 text-slate-400 leading-relaxed border-t border-white/5 mt-2">
                      {faq.answer}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="mt-16 text-center">
            <p className="text-slate-400 mb-4">Still have questions?</p>
            <Link to="/support" className="inline-flex items-center justify-center px-6 py-3 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-full font-medium transition-colors">
              Contact Support
            </Link>
          </div>
        </main>

        <div className="border-t border-white/10 bg-black/50 backdrop-blur-md">
          <Footer />
        </div>
      </div>
    </div>
  );
}
